const data = {
  products: [
    {
      id: 1,
      name: 'Free Shirt',
      slug: 'free-shirt',
      category: 'Shirts',
      image: '/images/prdimg.png',
      price: 50,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 9,
      countInStock: 50,
      description: 'A popular product',
      isFeatured: true,
      banner: '/images/banner1.jpg',
    },
    {
      id: 2,
      name: 'Free Shirt 2',
      slug: 'free-shirt',
      category: 'Shirts',
      image: '/images/prdimg.png',
      price: 50,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 9,
      countInStock: 50,
      description: 'A popular product',
      isFeatured: true,
      banner: '/images/banner1.jpg',
    },
    {
      id: 3,
      name: 'Free Shirt 3',
      slug: 'free-shirt',
      category: 'Shirts',
      image: '/images/prdimg.png',
      price: 50,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 9,
      countInStock: 50,
      description: 'A popular product',
      isFeatured: true,
      banner: '/images/banner1.jpg',
    },
    {
      id: 4,
      name: 'Free Shirt 4',
      slug: 'free-shirt',
      category: 'Shirts',
      image: '/images/prdimg.png',
      price: 50,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 9,
      countInStock: 50,
      description: 'A popular product',
      isFeatured: true,
      banner: '/images/banner1.jpg',
    },
    {
      id: 5,
      name: 'Free Shirt 5',
      slug: 'free-shirt',
      category: 'Shirts',
      image: '/images/prdimg.png',
      price: 50,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 9,
      countInStock: 50,
      description: 'A popular product',
      isFeatured: true,
      banner: '/images/banner1.jpg',
    },
  ],
}

export default data
